#Esto es un comentario... 
x = int(input("Ingrese un valor para x: "))
y = int(input("ingrese un valor para y: "))
z = ((1 + x / (y + x) / (1+x))/ y + 1)**3
print("El valor de z es: " , z)
#Este fue un calculo matemático... 
